### ISSUE TITLE
Resoconto al giorno 11/01

### ISSUE THREAD

**Issue by T0nyAbb** [T0nyAbb/LabManager#1]
Piccolo resoconto con i progressi fatti:

-Capitolo 2 della documentazione:

1. Class diagram
2. Ristrutturazione
3. Class Diagram ristrutturato
4. Dizionario delle classi (Da correggere qualche dettaglio)
5. Dizionario delle associazioni (Da controllare)
6. Dizionario dei vincoli (Da controllare)
------------------------------------------------
-Capitolo 3 della documentazione:

1. Traduzione in schema logico (Da completare l'introduzione)
2. Schema logico (Da controllare)

------------------------------------------------

-Create le prime tabelle in SQL

(Penso di finire entro oggi le tabelle e entro domani massimo finisco i trigger e le procedure varie)

------------------------------------------------
Alcuni dubbi:
-L'attributo 'campo' presente nella classe sede si riferisce all'ambito del laboratorio? Es: Chimico, Scientifico?
Se si allora va spostato in 'laboratorio' secondo me, siccome non ha a che vedere con la sede
-Anche l'attributo 'AnnoFondazione' va spostato in laboratorio o al massimo può essere rinominato in 'AnnoApertura' 

-Per quanto riguarda il vincolo del tempo massimo di utilizzo di uno strumento: Per crearlo va usato un trigger, di conseguenza credo che sia meglio aggiungere un attributo tempoMax alla classe strumento in modo che abbiamo più flessibilità per i tempi massimi per strumenti di diverso tipo (Es: Strumento=Miscelatore->TempoMax=15; Strumento=Microscopio->TempoMax=60) alla fine per implementare questa mia versione basta solo aggiungere una select all'interno del trigger, quindi non si complica neanche tanto il codice. 

Documentazione da rifinire o rivedere:
-Aggiornare l'indice
-Inserire l'introduzione ai capitoli
-Controllare che il documento sia formattato correttamente(?)

-Proporre qualche vincolo che sicuramente mi sarà sfuggito (ho messo tutti quelli che mi venivano in mente)

**Comment by T0nyAbb** [comment]
Aggiornamento al 12/01
-Completato il file struttura sql
-Controllata la corretta esecuzione dei trigger/funzioni
-Testate le insert sul database
-"Completato" il file popolamento sql
-Risolti alcuni problemi incontrati in fase di insert dei dati

Alcuni problemi che ho notato inserendo i dati:
L'attributo indirizzo è un attributo strutturato, (me ne sono accorto tardi lol) di conseguenza può essere trattato come unica stringa oppure come vorrei fare io è spezzettarlo in più attributi Es: Città,CAP,Indirizzo

sono propenso a fare così ma altre soluzioni sono ben accette.

La classe sede non ha un attributo nome (dal punto di vista di un utente l'unico attributo che contraddistingue due sedi è solo l'indirizzo)
Soluzione: aggiungere un attributo nome

Tutto sommato siamo a buon punto, il grosso del lavoro è già stato fatto bisogna solo rifinire qualche dettaglio

Poi tocca ad Object :)

**Comment by leokm02** [comment]
Rifiniti i dettagli per BDD:

CLASS DIAGRAM:
- Laboratorio ha gli attributi Campo e DataFondazione prima appartenenti alla classe Sede, (Campo indica la branca di studi del laboratorio: "Chimica", "Biologia", ...)
- Sede non ha un attributo nome ma l'indirizzo dovrebbe bastare per i fini del progetto
- Postazione ha attributo Nome(string) che sostituisce Numero(int)
- Prenotazione non ha più DataFine per ridondanza, inoltre Durata(int) indica la durata in ore
- Utente ha Username come unica chiave primaria

DOCUMENTAZIONE:
- Aggiornamento grafico (Ho preso spunto da progetti passati)
- Indice aggiornato
- Modifiche ai dizionari di classi e di associazioni
- Modifiche al dizionario di vincoli con aggiunta/rimozione di alcuni vincoli

DB STRUTTURA:
- Modifiche appropriate alla struttura interna delle tabelle
- Riscritti alcuni vincoli come CONSTRAINT all'interno delle tabelle
- Per semplificare la struttura del database ho pensato di implementare il vincolo di valore massimo come un CONSTRAINT all'interno della tabella PRENOTAZIONE

DB POPOLAMENTO:
- Aggiunti più statement di tipo INSERT sulla tabella PRENOTAZIONI





TODO:
- Riempire il file di testo README nella cartella sql
- Aggiungere view per il riepilogo di utilizzo strumenti (in sql/sql-struttura e nel Capitolo 4 di doc/Documentazione)
- Aggiungere trigger e funzioni in Capitolo 4 di doc/Documentazione
- Aggiungere Capitolo 5 "Manuale d'uso" in doc/Documentazione




Mi resta un unico dubbio sulla parte di crittografia password, perché mi sembra una procedura abbastanza complicata da implementare. Inoltre non saprei quali effetti avrebbe sulla progettazione lato Object Orientation, quindi penso sarebbe meglio memorizzare le password come stringhe tradizionali per rendere il tutto piu' semplice

Con Basi di Dati avrei quasi finito, per domani dovrei riuscire a completare i compiti segnati in TODO. Poi si può passare alla progettazione di Object Orientation 👍
