### ISSUE TITLE
Resoconto 30/01

### ISSUE THREAD

**Issue by leokm02** [T0nyAbb/LabManager#2]
Progressi:

- Aggiunta classe Controller [control]
- Aggiunte classi per la gestione di ecczioni [exceptions]
- Aggiunte classi relative all'implementazione GUI [gui.frames, gui.panels, gui.buttons]
- Aggiunte classi DTO [dto]
- Aggiunte classi DAO [dao]
- Aggiunta classe singleton per la connessione al database [DBconnection]
- Aggiunti file immagine per [background] e [icone]

---

TODO:

- Implementare un sistema di gestione prenotazioni in LabManager
- Aggiornare il class diagram per OO
- Aggiornare la documentazione per OO:
    1.  Aggiungere testo ai paragrafi di introduzione di capitolo
    2. Aggiungere Class diagram
    3. Aggiungere CRC Cards per tutte le classi
    4. Aggiungere 2 Sequence Diagrams

---

Direi che siamo a buon punto con la parte di Object del progetto. Ho dovuto fare alcune modifiche lievi a livello struttura database per rendere piu' semplice il lavoro di GUI. Ora comincio a lavorare sulla parte di gestione prenotazioni nell'app e aggiornero' il class diagram con le nuove classi e associazioni. Nel frattempo si dovrebbe aggiornare anche la documentazione OO

**Comment by T0nyAbb** [comment]
# Codice Date Picker
## Supporta la scelta della data ma non dell'ora quindi non è obbligatorio utilizzarlo.

````
import java.awt.*;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.time.Month;
import java.time.MonthDay;
import java.time.Year;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.*;
import javax.swing.border.LineBorder;


//create class

public class DatePicker extends JDialog
{
    private static final long serialVersionUID = 1L;
   
//define variables
    int month = 0;
    int year = 2023;
   
 //create object of JLabel with alignment
    JTextField textFieldDisplay = new JTextField("", JTextField.CENTER);
    
//define variable
    String day = "";
    
//create object of JButton
    JButton[] button = new JButton[49];

public DatePicker(JFrame parent)//create constructor
    {
        setAlwaysOnTop(true);
        ActionListener esciShortcut = new ActionListener(){
            public void actionPerformed(ActionEvent ae){
                dispose();
            }
        };
        getRootPane().registerKeyboardAction(esciShortcut, "command", KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0),
                JComponent.WHEN_IN_FOCUSED_WINDOW);
        //set modal true
        setModal(true);
        //define string
        String[] header = { "Dom", "Lun", "Mar", "Mer", "Gio", "Ven", "Sab" };
        //create JPanel object and set layout
        JPanel p1 = new JPanel(new GridLayout(7, 7));
        //set size
        p1.setPreferredSize(new Dimension(420, 200));
        p1.setBackground(Color.WHITE);
        //for loop condition
        for (int x = 0; x < button.length; x++)
        {
            //define variable
            final int selection = x;
            //create object of JButton
            button[x] = new JButton();
            //set focus painted false
            button[x].setFocusPainted(false);

            button[x].setOpaque(false);
            button[x].setContentAreaFilled(false);
            button[x].setFont(new Font("Roboto", Font.PLAIN, 12));
            button[x].setBorder(new LineBorder(Color.DARK_GRAY));

            //set background colour
            button[x].setBackground(Color.white);
            //if loop condition
            if (x > 6)
                //add action listener
                button[x].addActionListener(new ActionListener()
                {
                    public void actionPerformed(ActionEvent ae)
                    {
                        day = button[selection].getActionCommand();
                        //call dispose() method
                        dispose();
                    }
                });
            if (x < 7)//if loop condition
            {
                button[x].setText(header[x]);
                //set fore ground colour
                button[x].setForeground(new Color(64,151,0));
            }
            p1.add(button[x]);//add button
        }
        //create JPanel object with grid layout
        JPanel p2 = new JPanel(new GridLayout(1, 5));

        textFieldDisplay.setHorizontalAlignment(SwingConstants.CENTER);

        //create object of button for previous month
        JButton previousMonth = new JButton("<");
        //add action command
        previousMonth.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ae)
            {
                //decrement month by 1
                month--;
                //call method
                displayDate();
            }
        });

        JButton previousYear = new JButton("<<");
        previousYear.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae)
            {
                //decrement month by 1
                year--;
                //call method
                displayDate();
            }
        });

        JButton nextYear = new JButton(">>");
        nextYear.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent ae)
            {
                //decrement month by 1
                year++;
                //call method
                displayDate();
            }
        });


        //create object of button for next month
        JButton nextMonth = new JButton(">");
        //add action command
        nextMonth.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent ae)
            {
                //increment month by 1
                month++;
                //call method
                displayDate();
            }
        });


        p2.add(previousYear);
        p2.add(previousMonth);
        p2.add(textFieldDisplay);
        p2.add(nextMonth);
        p2.add(nextYear);

        previousYear.setBorderPainted(false);
        previousMonth.setBorderPainted(false);
        nextMonth.setBorderPainted(false);
        nextYear.setBorderPainted(false);

        previousYear.setFocusPainted(false);
        previousMonth.setFocusPainted(false);
        nextMonth.setFocusPainted(false);
        nextYear.setFocusPainted(false);

        previousYear.setBackground(Color.WHITE);
        previousMonth.setBackground(Color.WHITE);
        nextMonth.setBackground(Color.WHITE);
        nextYear.setBackground(Color.WHITE);

        textFieldDisplay.setBorder(new LineBorder(Color.WHITE));


        textFieldDisplay.setEditable(false);
        setBackground(Color.WHITE);
        setUndecorated(true);
        setResizable(false);
        textFieldDisplay.setBackground(Color.WHITE);

        //set border alignment
        getContentPane().add(p1, BorderLayout.CENTER);
        getContentPane().add(p2, BorderLayout.SOUTH);
        pack();
        //set location
        setLocationRelativeTo(parent);
        //call method
        displayDate();
        //set visible true
        setVisible(true);
    }

    public void displayDate()
    {
        for (int x = 7; x < button.length; x++)//for loop
            button[x].setText("");//set text
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        //create object of SimpleDateFormat
        java.util.Calendar cal = java.util.Calendar.getInstance();
        SimpleDateFormat fdate = new SimpleDateFormat("yyyy/MM/dd HH:mm", Locale.ITALY);



        //create object of java.util.Calendar
        cal.set(year, month, 1); //set year, month and date
        //define variables
        int dayOfWeek = cal.get(java.util.Calendar.DAY_OF_WEEK);
        int daysInMonth = cal.getActualMaximum(java.util.Calendar.DAY_OF_MONTH);
        //condition
        for (int x = 6 + dayOfWeek, day = 1; day <= daysInMonth; x++, day++)
            //set text
            button[x].setText("" + day);
        textFieldDisplay.setText(sdf.format(cal.getTime()));
        //set title
        setTitle("Date Picker");
    }

    public String setPickedDate()
    {
        //if condition
        if (day.equals(""))
            return day;
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        java.util.Calendar cal = java.util.Calendar.getInstance();
        cal.set(year, month, Integer.parseInt(day));
        return sdf.format(cal.getTime());
    }}`

**Comment by T0nyAbb** [comment]
Un consiglio per la dashboard:

- Aggiungere un attributo alla classe controller di tipo utente chiamato currentUser (se gia è presente ignorare)
- Una volta effettuato il login il currentUser sarà l'utente che si è loggato 
- Servirà per creare le label dinamiche nella dashboard del tipo: "Ciao `currentUser.getUsername();` ecco le tue statistiche/prenotazioni:"
- una volta effettuato il logout poi la variabile verrà settata a null

**Comment by T0nyAbb** [comment]
## Update:

- Statistiche

Ho finito di scrivere i metodi e le viste per la parte di statistiche, l'unica cosa che manca da fare è l'interfaccia grafica in se, siccome eclipse non mi consente di compilare, di testare e di modificare i panel non posso fare molto con le gui quindi allego solo una foto di come dovrebbe venire l'interfaccia

NB: le query e i metodi li ho già scritti quindi bisogna solo implementarli nel panel e testarli 
(si trovano nella classe statsStrumento)



![image](https://user-images.githubusercontent.com/120809118/217004813-600d1276-2436-484e-88a0-7f37b4dce738.png)

La traccia inoltre chiede che quando viene selezionato uno strumento sia mostrato un calendario di prenotazione per quello strumento

Io direi di aggiungere un pulsante sopra quello di effettua prenotazione (o anche di fianco) nel panel della prenotazione con scritto mostra calendario (o qualcosa del genere) che se cliccato apre una JDialog (come quella di modifica prenotazione) che all'interno avrà una JList con tutte le prenotazioni fatte. Credo che sia la soluzione più veloce/semplice siccome riutilizza parecchio codice già scritto ma altre idee sono ben accette.

L'altra cosa che chiede la traccia è che quando un utente sceglie strumento data e ora quando prenota siano mostrate le sedi e gli slot disponibili alla prenotazione. Io direi di mettere una Label sotto lo spinner dell'ora che mostrerà in base allo strumento scelto e alla data: "Lo strumento scelto è prenotabile negli slot: `getPostazione() + getSede()` " oppure "non sono disponibili slot nella data specificata"
Come detto prima mi sembra la soluzione più veloce ma anche qui libera scelta

**Comment by leokm02** [comment]
Aggiunti i componenti alla classe StrumentoStatsPanel, ora sono visibili e pronti per l'interazione con l'utente.

Ho ritrovato un unico bug a livello database: il trigger NO_DOUBLE_PREN lancia un'eccezione quando si fa una update su uno strumento.

**Comment by T0nyAbb** [comment]
Ok mi sembra di capire che con le statistiche abbiamo finito quindi. (🥳)
non ho potuto testare se funziona tutto siccome mi manca la classe style.java

Riguardo il bug che fa scattare il trigger, intendi quando si tenta di modificare una prenotazione per uno strumento? 
Se si mi basta solo cancellare la riga di codice che fa scattare il trigger anche quando si fa una update.

**Comment by leokm02** [comment]
Ok grazie per l'avviso, ho fatto un commit con tutte le classi mancanti.
Comunque riguardo il bug, quando provo a modificare la data ora e la durata di una prenotazione dalla schermata HandleReservationPanel, mi da questo messaggio di errore:

![Cattura](https://user-images.githubusercontent.com/95973806/218335206-444ef862-b193-46b8-b0f0-8c1d1e358d2b.PNG)

Quindi penso si dovrebbe rivedere il trigger di NO_DOUBLE_PREN a livello database, perché vedo che è l'unico blocco che lancia quel tipo di eccezione.

**Comment by T0nyAbb** [comment]
L'ho appena fixato, ora dovrebbe andare.

**Comment by T0nyAbb** [comment]
## Update:
Ho rivisto i class diagram che avevo fatto siccome il codice è stato aggiornato.
Inoltre ho aggiunto il metodo per ottenere il calendario di prenotazione per strumento.

Per terminare il class diagram e quindi la documentazione ho bisogno che l'app sia completata.
La scadenza è il 21 febbraio quindi il 20 dobbiamo finire (se riusciamo prima ancora meglio)
